### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by ColdSunERA** [PCGamingEra/pad#1]
- [ ] Content Types
- - [ ] Article
- - [ ] Basic Page
- - [ ] Blog
- - [ ] Story
- - [ ] Video
- [ ]  Comment Reply Banner
_Allow for timestamps and optional author display_
- - [ ] Content and Entity type independent
- - [ ] Permission based creation and viewing
- [ ] User node creation via WYSIWYG
- - [ ] Support local media uploading
- - [ ] Support Instagram, Twitter cards
- - [ ] Improved media handling with optional galleries and ability to see and re-use past submitted media
- - [ ] Drag and drop content to change position in submission
- - [ ] Preview mode to view how different devices will see the content
- [ ] Content Scheduling
- - [ ] Ability to publish content at set time
- - [ ] Ability to unpublish content at set time
- [ ] Live Blog
- [ ] Facebook Instant Articles
- [ ] Google AMP
